warp_mesh = "BeautyFaceSP.bsm2"

draw_order = ["TriAndroid", "!glfx_UPDATE_BG", "retouch"]

[materials.retouch]
vs = "retouch.vert"
fs = "retouch.frag"
blend = "off"
backfaces = false
colorwrite = true
zwrite = false
shadow = false
onface = true
mouth = true
[materials.retouch.samplers]
selection_tex="REDMASK_v3_256.png"
lookupTexTeeth="TEETH_medium.png"
lookupTexEyes="EYES_medium.png"
tex_highlight="FLARE_39_512.png"

[materials.TriAndroid]
vs = "hair_a.vert"
fs = "hair.frag"
blend = "off" # "alpha", "premul_alpha", "screen", "add", "multiply"
backfaces = false
colorwrite = true
zwrite = false
shadow = false
samplers = {}