warp_mesh = "BeautyFaceSP.bsm2"

draw_order = ["Q0", "Q1", "!glfx_UPDATE_BG", "retouch"]

[materials.retouch]
vs = "retouch.vert"
fs = "retouch.frag"
blend = "off"
backfaces = false
colorwrite = true
zwrite = false
shadow = false
onface = true
mouth = true
[materials.retouch.samplers]
selection_tex="REDMASK_v3_256.png"
lookupTexTeeth="TEETH_medium.png"

[materials.Q0]
vs = "leye.vert"
fs = "leye.frag"
blend = "screen"
backfaces = true
colorwrite = true
zwrite = false
ztest = false
shadow = false
samplers = {}

[materials.Q1]
vs = "reye.vert"
fs = "reye.frag"
blend = "screen"
backfaces = true
colorwrite = true
zwrite = false
ztest = false
shadow = false
samplers = {}